### ISSUE TITLE
Datastore classic not properly working?

### ISSUE THREAD

**Issue by siemvaessen** [codeforIATI/iati-datastore#239] opened 2021-03-15 12:26 UTC
### Describe the bug

Go to: https://datastore.codeforiati.org/

Red banner states `Datastore has some problems`

I am downloading a transactions file only for Nigeria, but after 20 mins stuck at 95MB (still working)

Perhaps kick this machine a bit :-) wanted to see how many transactions were provided by Datastore Classic.

**Comment by andylolz** [comment] 2021-03-15 12:39
> Perhaps kick this machine a bit :-)

Thanks Siem – we spotted this earlier. The disk was full, due to a giant log file! It’s resolved, and is currently updating.

We don’t receive automatic reports when there’s a problem like this, though we did happen to spot this one yesterday. We should really auto-monitor [the relevant API URL](https://datastore.codeforiati.org/api/1/about/) and fire off an email when there’s a problem.

> I am downloading a transactions file only for Nigeria, but after 20 mins stuck at 95MB (still working)

That sounds like something different. Can you open a new ticket, and include the URL of the request you’re making? Thanks!

**Comment by siemvaessen** [comment] 2021-03-15 12:59
Ah ok, I just cancelled the download, 400MB file was still in progress. HUGE!

**Comment by andylolz** [comment] 2021-03-16 11:46
The updating issue looks resolved now, so closing this one. (Definitely still the case that generating CSV for download is too slow).

**Comment by andylolz** [comment] 2021-03-17 09:11
Reopening because the error message is back!

I’m pretty sure I know the cause. I was making changes to IATI data dump yesterday, and because I made an error, the new version of the zip file wasn’t created until about 5am, which was probably too late for DS Classic. This seems a bit messy, but in general IATI data dump is pretty reliable, so it’s rare that it’s the cause of this sort of problem.

Anyway – I’ll leave this open until the error message goes away (hopefully tomorrow!)

**Comment by andylolz** [comment] 2021-03-18 13:13
Okay yes – as hoped/expected, this has sorted itself out again. PHEW. Re-closing.

**Closed by andylolz** 2021-03-18 13:13 UTC
